export default {
  salons: [
    {
      'id': 1,
      'name': 'Estética Canina Ginari',
      'address': 'Enrique Rébsamen 221, Narvarte Poniente, 03020 Ciudad de México, CDMX',
      'longitude': '19.399934',
      'latitude': '-99.158848',
      'city': 'Ciudad de México',
      'phone': '55 5639 8387',
      'rating': 4.6,
      'reviews': 100,
      'short_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'full_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'services': ['Baño', 'Corte', 'Limpieza Dental', 'Tratamiento anti-pulgas', 'Corte para concurso'],
      'other_services': ['Veterinaria', 'Clínica', 'Pensión', 'Hospital', 'Transporte de tu mascota para servicios veterinarios y estéticos'],
      'images': [
        'http://dummyimage.com/951x584.bmp/cc0000/ffffff',
        'http://dummyimage.com/736x1040.jpg/cc0000/ffffff',
        'http://dummyimage.com/719x884.bmp/dddddd/000000',
        'http://dummyimage.com/1005x497.jpg/ff4444/ffffff',
      ],
    },
    {
      'id': 2,
      'name': 'Estética Canina',
      'address': 'Xola 1603, Narvarte Poniente, 03020 Ciudad de México, CDMX',
      'longitude': '19.406683',
      'latitude': '-99.151997',
      'city': 'Ciudad de México',
      'phone': '55 5538 1173',
      'rating': null,
      'reviews': null,
      'short_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'full_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'services': ['Baño', 'Corte', 'Limpieza Dental', 'Tratamiento anti-pulgas', 'Corte para concurso'],
      'other_services': ['Veterinaria', 'Clínica', 'Pensión', 'Hospital', 'Transporte de tu mascota para servicios veterinarios y estéticos'],
      'images': [
        'http://dummyimage.com/951x584.bmp/cc0000/ffffff',
        'http://dummyimage.com/736x1040.jpg/cc0000/ffffff',
        'http://dummyimage.com/719x884.bmp/dddddd/000000',
        'http://dummyimage.com/1005x497.jpg/ff4444/ffffff',
      ],
    },
    {
      'id': 3,
      'name': 'Estetica Canina Burbujitas',
      'address': 'Luna 200, Buenavista, 06350 Buenavista, CDMX',
      'longitude': '19.459788',
      'latitude': '-99.146507',
      'city': 'Ciudad de México',
      'phone': null,
      'rating': 4.4,
      'reviews': 10,
      'short_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'full_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'services': ['Baño', 'Corte', 'Limpieza Dental', 'Tratamiento anti-pulgas', 'Corte para concurso'],
      'other_services': ['Veterinaria', 'Clínica', 'Pensión', 'Hospital', 'Transporte de tu mascota para servicios veterinarios y estéticos'],
      'images': [
        'http://dummyimage.com/951x584.bmp/cc0000/ffffff',
        'http://dummyimage.com/736x1040.jpg/cc0000/ffffff',
        'http://dummyimage.com/719x884.bmp/dddddd/000000',
        'http://dummyimage.com/1005x497.jpg/ff4444/ffffff',
      ],
    },
    {
      'id': 4,
      'name': 'Acuamas Pet Shop, Veterinaria y Estética Canina',
      'address': 'Lorenzo Boturini 339-A, Tránsito, 06820 Ciudad de México, CDMX',
      'longitude': '19.426760',
      'latitude': '-99.130024',
      'city': 'Ciudad de México',
      'phone': '55 5741 7409',
      'rating': 4.3,
      'reviews': 68,
      'short_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'full_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'services': ['Baño', 'Corte', 'Limpieza Dental', 'Tratamiento anti-pulgas', 'Corte para concurso'],
      'other_services': ['Veterinaria', 'Clínica', 'Pensión', 'Hospital', 'Transporte de tu mascota para servicios veterinarios y estéticos'],
      'images': [
        'http://dummyimage.com/951x584.bmp/cc0000/ffffff',
        'http://dummyimage.com/736x1040.jpg/cc0000/ffffff',
        'http://dummyimage.com/719x884.bmp/dddddd/000000',
        'http://dummyimage.com/1005x497.jpg/ff4444/ffffff',
      ],
    },
    {
      'id': 5,
      'name': 'Estetica Canina Romeo',
      'address': 'Calle Monte Albán 25, Vértiz Narvarte, 03020 Ciudad de México, CDMX',
      'longitude': '19.402423',
      'latitude': '-99.1503360',
      'city': 'Ciudad de México',
      'phone': '55 5440 0204',
      'rating': 5,
      'reviews': 10,
      'short_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'full_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'services': ['Baño', 'Corte', 'Limpieza Dental', 'Tratamiento anti-pulgas', 'Corte para concurso'],
      'other_services': ['Veterinaria', 'Clínica', 'Pensión', 'Hospital', 'Transporte de tu mascota para servicios veterinarios y estéticos'],
      'images': [
        'http://dummyimage.com/951x584.bmp/cc0000/ffffff',
        'http://dummyimage.com/736x1040.jpg/cc0000/ffffff',
        'http://dummyimage.com/719x884.bmp/dddddd/000000',
        'http://dummyimage.com/1005x497.jpg/ff4444/ffffff',
      ],
    },
    {
      'id': 6,
      'name': 'Estética Canina Escuby-Doo',
      'address': 'Teniente Roberto Gómez Moreno 254, Escuadrón 201, 09060 Iztapalapa, CDMX',
      'longitude': '19.362561',
      'latitude': '-99.112233',
      'city': 'Ciudad de México',
      'phone': '55 2154 1421',
      'rating': 4.7,
      'reviews': 12,
      'short_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'full_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'services': ['Baño', 'Corte', 'Limpieza Dental', 'Tratamiento anti-pulgas', 'Corte para concurso'],
      'other_services': ['Veterinaria', 'Clínica', 'Pensión', 'Hospital', 'Transporte de tu mascota para servicios veterinarios y estéticos'],
      'images': [
        'http://dummyimage.com/951x584.bmp/cc0000/ffffff',
        'http://dummyimage.com/736x1040.jpg/cc0000/ffffff',
        'http://dummyimage.com/719x884.bmp/dddddd/000000',
        'http://dummyimage.com/1005x497.jpg/ff4444/ffffff',
      ],
    },
    {
      'id': 7,
      'name': 'Estetica Canina PetCare',
      'address': 'Calle Gral. Gómez Pedraza 3, San Miguel Chapultepec II Secc, 11850 Ciudad de México, CDMX',
      'longitude': '19.362561',
      'latitude': '-99.112233',
      'city': 'Ciudad de México',
      'phone': '55 4981 0853',
      'rating': 3.3,
      'reviews': 57,
      'short_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'full_description': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo ea repellendus accusantium aspernatur magnam enim sed recusandae.',
      'services': ['Baño', 'Corte', 'Limpieza Dental', 'Tratamiento anti-pulgas', 'Corte para concurso'],
      'other_services': ['Veterinaria', 'Clínica', 'Pensión', 'Hospital', 'Transporte de tu mascota para servicios veterinarios y estéticos'],
      'images': [
        'http://dummyimage.com/951x584.bmp/cc0000/ffffff',
        'http://dummyimage.com/736x1040.jpg/cc0000/ffffff',
        'http://dummyimage.com/719x884.bmp/dddddd/000000',
        'http://dummyimage.com/1005x497.jpg/ff4444/ffffff',
      ],
    },
  ],
};
